name: Node.js Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          
      - name: Install dependencies
        run: npm install --production

      - name: Run Tests
        run: npm test --if-present

      - name: Archive production files
        run: |
          rm -rf release
          mkdir -p release
          shopt -s extglob
          cp -r !(release) release/
          tar -czf release.tar.gz -C release .


      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "release.tar.gz"
          target: "~/app/"

          
      - name: Deploy on VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            mkdir -p ~/app/deploy
            tar -xzf ~/app/release.tar.gz -C ~/app/deploy
            cd ~/app/deploy
            npm install --production
            pm2 delete backend || true
            # Start new process on port 80
            pm2 start npm --name "backend" -- start
